import { useMemo, useState } from 'react';
import { GitBranch } from 'lucide-react';
import { Link } from 'react-router-dom';
import { useWellContext } from '../../hooks/useWellContext';
import { collectCases } from '../../data/intelligenceCasework';
import type { EventType } from '../../types';
import { EmptyNotice, IntelligenceFeatureLayout, Panel, SelectField } from '../../components/intelligence/IntelligenceUI';

const eventTypes: (EventType | 'ALL')[] = ['ALL', 'Mud Loss', 'Stuck Pipe', 'Kick', 'Torque Spike', 'Cementing Issue', 'Fishing', 'NPT'];

export function KnowledgeGraphPage() {
  const { activeWell, nearbyWells } = useWellContext();
  const [formation, setFormation] = useState('ALL');
  const [eventType, setEventType] = useState<EventType | 'ALL'>('ALL');
  const [depth, setDepth] = useState(activeWell.currentDepth ?? 0);
  const [query, setQuery] = useState('');
  const [eventId, setEventId] = useState('');
  const cases = useMemo(() => collectCases([activeWell, ...nearbyWells]).filter(({ well, event }) => (formation === 'ALL' || event.formation === formation || (!well.isUnresolved && well.formation === formation)) && Math.abs(event.depth - depth) <= 500 && (eventType === 'ALL' || event.eventType === eventType) && `${well.id} ${well.name} ${well.formation} ${event.eventType} ${event.depth} ${event.sourceDocument}`.toLowerCase().includes(query.toLowerCase())).sort((a, b) => Math.abs(a.event.depth - depth) - Math.abs(b.event.depth - depth)), [activeWell, nearbyWells, formation, eventType, depth, query]);
  const selected = cases.find(({ event }) => event.id === eventId) ?? cases[0];
  return <IntelligenceFeatureLayout featureId="graph" title="Drilling Knowledge Graph" summary="Explore relationships derived from the records already in NWIS: wells, formations, depth intervals, events, source references, and attached evidence.">
    <Panel title="Find graph relationships" subtitle="Search entity names and filter by formation, event type, and nearby depth." icon={GitBranch}><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><label className="text-xs font-medium text-slate-500">Search entities<input value={query} onChange={(event) => setQuery(event.target.value)} className="mt-1 block w-full rounded-md border border-border-default bg-surface-elevated px-3 py-2 text-sm text-white" placeholder="Well, event, source ID" /></label><SelectField label="Formation" value={formation} onChange={setFormation}><option value="ALL">All formations</option>{['F1','F2','F3','F4','F5'].map((item) => <option key={item} value={item}>{item}</option>)}</SelectField><SelectField label="Event type" value={eventType} onChange={(value) => setEventType(value as EventType | 'ALL')}>{eventTypes.map((item) => <option key={item} value={item}>{item === 'ALL' ? 'All event types' : item}</option>)}</SelectField><label className="text-xs font-medium text-slate-500">Depth center · {depth.toLocaleString()} m<input type="range" min="0" max={activeWell.totalDepth} step="10" value={depth} onChange={(event) => setDepth(Number(event.target.value))} className="mt-3 block w-full accent-cyan-700" /></label></div></Panel>
    {!selected ? <EmptyNotice>No graph relationships match these filters.</EmptyNotice> : <Panel title="Connected case graph" subtitle={`${cases.length} related historical event record(s) in the filtered dataset.`}>
      <div className="grid gap-3 sm:grid-cols-2 2xl:grid-cols-3">{cases.slice(0, 12).map(({ well, event }) => <button key={event.id} onClick={() => setEventId(event.id)} className={`rounded-lg border p-3 text-left transition-colors ${selected.event.id === event.id ? 'border-accent-500 bg-accent-500/5' : 'border-border-default bg-surface-elevated hover:border-accent-500/40'}`}><p className="text-xs font-semibold text-white">{well.id} <span className="font-normal text-slate-500">— HAS_FORMATION → {well.formation}</span></p><p className="mt-2 text-xs text-slate-500">{well.id} — EXPERIENCED_EVENT → <b className="text-white">{event.eventType}</b></p><p className="mt-1 text-xs text-slate-500">{event.eventType} — AT_DEPTH → {event.depth} m</p><p className="mt-1 truncate text-xs text-slate-500">{event.eventType} — DOCUMENTED_BY → {event.sourceDocument || 'source unavailable'}</p></button>)}</div>
      <div className="mt-5 rounded-xl border border-border-default bg-surface-elevated p-4"><p className="mb-3 text-xs font-semibold text-white">Selected relationship path</p><div className="flex flex-wrap items-center gap-2">{[[activeWell.id,'CURRENT WELL'],[activeWell.formation,'FORMATION'],[selected.well.id,'OFFSET WELL'],[selected.event.eventType,'EVENT'],[`${selected.event.depth} m`,'DEPTH'],[selected.event.sourceDocument || 'No source','SOURCE']].map(([value,label], index) => <div key={`${label}-${value}`} className="flex items-center gap-2"><div className="rounded-lg border border-border-default bg-surface-card px-3 py-2"><p className="text-[9px] font-bold text-accent-700">{label}</p><p className="text-xs font-semibold text-white">{value}</p></div>{index < 5 && <span className="text-accent-500">→</span>}</div>)}</div><div className="mt-4 flex flex-wrap gap-4 text-xs"><Link to={`/intelligence/evidence?wellId=${encodeURIComponent(selected.well.id)}&eventId=${encodeURIComponent(selected.event.id)}`} className="font-semibold text-accent-600 hover:underline">Open evidence chain →</Link><Link to={`/intelligence/fingerprint?wellId=${encodeURIComponent(selected.well.id)}&eventId=${encodeURIComponent(selected.event.id)}`} className="font-semibold text-accent-600 hover:underline">Open case fingerprint →</Link></div></div>
      <p className="mt-3 text-[10px] text-slate-500">Edges are visualized from available record fields; a source-reference string is not a verified report attachment. Missing relationships are not inferred.</p>
    </Panel>}
  </IntelligenceFeatureLayout>;
}
